#!/usr/bin/env bash
#
# Red/green suite for the SHAPE OF THE MEMORY NETWORK block in .githooks/pre-commit.
#
#   .githooks/tests/shape-gate.test.sh
#
# Why this file exists: the block it tests spent its whole life below a bare
# `exit 0` and never executed once. It looked correct in review every time,
# because reading a hook top to bottom is not the same as running it. Shipping
# bible law 1: a gate you have never watched fail is not a gate.
#
# Every case builds a THROWAWAY git repo in a temp dir and runs the real hook
# inside it against a STUB generator, so nothing here touches the real memory
# network, the real generator, or this repo's index.

set -uo pipefail

HOOK="$(cd "$(dirname "$0")/.." && pwd)/pre-commit"
[ -f "$HOOK" ] || { echo "cannot find pre-commit next to this test"; exit 1; }

pass=0
fails=()
check() { # name, condition-already-evaluated (0/1), detail
  if [ "$2" -eq 0 ]; then pass=$((pass + 1)); else fails+=("$1${3:+: $3}"); fi
}

# A throwaway repo with the hook's other gates satisfied, plus a fake $HOME
# holding a stub generator that behaves however the case needs.
#   $1 = generator behavior: "writes" | "refuses" | "absent"
#   $2 = "tracked" to commit a docs/images/memory-shape.svg first, else omitted
make_repo() {
  local behavior="$1" tracked="${2:-untracked}"
  local dir; dir="$(mktemp -d "${TMPDIR:-/tmp}/shape-gate.XXXXXX")"
  mkdir -p "$dir/repo/.githooks" "$dir/home/.claude/scripts/memory"
  cp "$HOOK" "$dir/repo/.githooks/pre-commit"
  chmod +x "$dir/repo/.githooks/pre-commit"
  # The bleed gate refuses an empty denylist, so give it a term nothing here uses.
  printf 'averyprivatecodename\n' > "$dir/repo/.githooks/denylist.local"

  local gen="$dir/home/.claude/scripts/memory/graph-anon.mjs"
  case "$behavior" in
    writes)  printf '#!/bin/sh\nprintf "<svg>regenerated</svg>" > "$3"\n' > "$gen"; chmod +x "$gen" ;;
    refuses) printf '#!/bin/sh\nexit 1\n' > "$gen"; chmod +x "$gen" ;;
    absent)  : ;;
  esac

  git -C "$dir/repo" init -q
  git -C "$dir/repo" config user.email t@t.t
  git -C "$dir/repo" config user.name t
  if [ "$tracked" = "tracked" ]; then
    mkdir -p "$dir/repo/docs/images"
    printf '<svg>stale</svg>' > "$dir/repo/docs/images/memory-shape.svg"
    git -C "$dir/repo" add docs/images/memory-shape.svg
    git -C "$dir/repo" commit -qm "seed" --no-verify
  fi
  printf 'a line\n' > "$dir/repo/note.md"
  git -C "$dir/repo" add note.md
  printf '%s\n' "$dir"
}

# The stub generator is a shell script, not node, so run the hook with a PATH
# where `node` just execs its first argument. The hook calls
#   node <gen> --linked-only --out <shape>
# so the stub sees three arguments and the out path is "$3".
run_hook() {
  local dir="$1"
  mkdir -p "$dir/bin"
  printf '#!/bin/sh\nexec "$@"\n' > "$dir/bin/node"
  chmod +x "$dir/bin/node"
  ( cd "$dir/repo" && HOME="$dir/home" PATH="$dir/bin:$PATH" ./.githooks/pre-commit 2>&1 )
}

# ── 1. GREEN: tracked picture + working generator = regenerated AND re-staged.
d="$(make_repo writes tracked)"
out="$(run_hook "$d")"; rc=$?
check "green: hook exits 0" "$([ $rc -eq 0 ] && echo 0 || echo 1)" "exit $rc, output: $out"
staged="$(git -C "$d/repo" diff --cached --name-only)"
case "$staged" in *docs/images/memory-shape.svg*) r=0 ;; *) r=1 ;; esac
check "green: the picture is re-staged by the hook" "$r" "staged: $(echo "$staged" | tr '\n' ' ')"
case "$(cat "$d/repo/docs/images/memory-shape.svg")" in *regenerated*) r=0 ;; *) r=1 ;; esac
check "green: the picture is the regenerated bytes, not the stale ones" "$r"
rm -rf "$d"

# ── 2. RED: the generator refusing is a HARD STOP, not a warning.
# This is the case the block exists for. It has never once run in production.
d="$(make_repo refuses tracked)"
out="$(run_hook "$d")"; rc=$?
check "red: refusing generator blocks the commit" "$([ $rc -ne 0 ] && echo 0 || echo 1)" "exit $rc"
case "$out" in *"refused to write"*) r=0 ;; *) r=1 ;; esac
check "red: it says WHY and how to reproduce" "$r" "output: $out"
rm -rf "$d"

# ── 3. Generator absent: silent skip. Anyone who clones this repo has no such
# script on their machine and their commits must not fail because of it.
d="$(make_repo absent tracked)"
out="$(run_hook "$d")"; rc=$?
check "absent generator: commit still allowed" "$([ $rc -eq 0 ] && echo 0 || echo 1)" "exit $rc, output: $out"
case "$out" in *BLOCKED*) r=1 ;; *) r=0 ;; esac
check "absent generator: says nothing" "$r" "output: $out"
rm -rf "$d"

# ── 4. Portability: a repo that does not track the picture never grows one.
# The kit gets copied into other public-bound repos. On the machine where the
# generator IS installed, an unguarded block would drop a network picture into
# a repo that never asked for one, on its next commit.
d="$(make_repo writes untracked)"
out="$(run_hook "$d")"; rc=$?
check "untracked: commit still allowed" "$([ $rc -eq 0 ] && echo 0 || echo 1)" "exit $rc, output: $out"
r=1; [ ! -e "$d/repo/docs/images/memory-shape.svg" ] && r=0
check "untracked: no picture appears in a repo that never had one" "$r"
rm -rf "$d"

echo ""
if [ ${#fails[@]} -eq 0 ]; then
  echo "shape gate: ${pass} checks passed."
  exit 0
fi
echo "shape gate: ${pass} passed, ${#fails[@]} FAILED"
for f in "${fails[@]}"; do echo "  - $f"; done
exit 1
